name: go test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - run: go test ./...